sudo: required
install: true
language: node_js
node_js:
  - '8'
services:
  - docker
before_install:
  - docker-compose -f ./scripts/docker-compose.yml -f ./scripts/docker-compose.ci.yml build
  - docker-compose -f ./scripts/docker-compose.yml -f ./scripts/docker-compose.ci.yml up -d
script: 
  - docker-compose -f ./scripts/docker-compose.yml -f ./scripts/docker-compose.ci.yml exec bot sh -c 'npm run test'
after_success:
  - docker-compose -f ./scripts/docker-compose.yml -f ./scripts/docker-compose.ci.yml exec bot sh -c 'npm run coverage'
after_script:
  - docker-compose -f ./scripts/docker-compose.yml -f ./scripts/docker-compose.ci.yml down