version: "3"
services:
  bot:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
    depends_on:
      - mongodb
    command: tail -f /usr/app/yarn.lock
    environment:
      - "NODE_ENV=development"
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
      - "DISCORD_ID=${DISCORD_ID}"
      - "OWNER_ID=${OWNER_ID}"

  mongodb:
    image: mongo
    ports:
      - 27017:27017