version: "3"
services:
  bot:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
    command: npm start
    depends_on:
      - mongodb
    links:
      - mongodb
    env_file:
      - .env
    ports:
      - 5858:5858

  mongodb:
    image: mongo
    ports:
      - 27018:27017
  
  mongo-backup:
    image: "istepanov/mongodump:3.4"
    volumes:
      - mongo-backup:/backup
    environment:
      CRON_SCHEDULE: '0 1 * * *'
    depends_on:
      - mongodb

volumes:
  mongo-backup: