version: "3"
services:
  bot:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
    command: npm run dev
    depends_on:
      - mongodb
    links:
      - mongodb
    env_file:
      - development.env
    ports:
      - 5858:5858

  mongodb:
    image: mongo
    ports:
      - 27017:27017