version: "3"
services:
  bot:
    build: .
    volumes:
      - .:/usr/app
    command: npm run dev
    depends_on:
      - mongodb
    links:
      - mongodb
    env_file:
      - developement.env

  mongodb:
    image: mongo
    ports:
      - 27017:27017