// flow-typed signature: 922f84d08f6d3583db54cfa05b63e330
// flow-typed version: <<STUB>>/discord.js-commando_v0.10.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'discord.js-commando'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'discord.js-commando' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'discord.js-commando/src/client' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/argument' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/base' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/collector' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/commands/disable' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/commands/enable' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/commands/groups' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/commands/load' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/commands/reload' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/commands/unload' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/group' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/message' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/util/eval' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/util/help' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/util/ping' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/commands/util/prefix' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/dispatcher' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/errors/command-format' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/errors/friendly' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/extensions/guild' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/index' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/providers/base' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/providers/helper' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/providers/sqlite' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/registry' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/base' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/boolean' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/channel' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/command' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/float' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/group' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/integer' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/member' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/message' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/role' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/string' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/union' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/types/user' {
  declare module.exports: any;
}

declare module 'discord.js-commando/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'discord.js-commando/src/client.js' {
  declare module.exports: $Exports<'discord.js-commando/src/client'>;
}
declare module 'discord.js-commando/src/commands/argument.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/argument'>;
}
declare module 'discord.js-commando/src/commands/base.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/base'>;
}
declare module 'discord.js-commando/src/commands/collector.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/collector'>;
}
declare module 'discord.js-commando/src/commands/commands/disable.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/commands/disable'>;
}
declare module 'discord.js-commando/src/commands/commands/enable.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/commands/enable'>;
}
declare module 'discord.js-commando/src/commands/commands/groups.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/commands/groups'>;
}
declare module 'discord.js-commando/src/commands/commands/load.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/commands/load'>;
}
declare module 'discord.js-commando/src/commands/commands/reload.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/commands/reload'>;
}
declare module 'discord.js-commando/src/commands/commands/unload.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/commands/unload'>;
}
declare module 'discord.js-commando/src/commands/group.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/group'>;
}
declare module 'discord.js-commando/src/commands/message.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/message'>;
}
declare module 'discord.js-commando/src/commands/util/eval.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/util/eval'>;
}
declare module 'discord.js-commando/src/commands/util/help.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/util/help'>;
}
declare module 'discord.js-commando/src/commands/util/ping.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/util/ping'>;
}
declare module 'discord.js-commando/src/commands/util/prefix.js' {
  declare module.exports: $Exports<'discord.js-commando/src/commands/util/prefix'>;
}
declare module 'discord.js-commando/src/dispatcher.js' {
  declare module.exports: $Exports<'discord.js-commando/src/dispatcher'>;
}
declare module 'discord.js-commando/src/errors/command-format.js' {
  declare module.exports: $Exports<'discord.js-commando/src/errors/command-format'>;
}
declare module 'discord.js-commando/src/errors/friendly.js' {
  declare module.exports: $Exports<'discord.js-commando/src/errors/friendly'>;
}
declare module 'discord.js-commando/src/extensions/guild.js' {
  declare module.exports: $Exports<'discord.js-commando/src/extensions/guild'>;
}
declare module 'discord.js-commando/src/index.js' {
  declare module.exports: $Exports<'discord.js-commando/src/index'>;
}
declare module 'discord.js-commando/src/providers/base.js' {
  declare module.exports: $Exports<'discord.js-commando/src/providers/base'>;
}
declare module 'discord.js-commando/src/providers/helper.js' {
  declare module.exports: $Exports<'discord.js-commando/src/providers/helper'>;
}
declare module 'discord.js-commando/src/providers/sqlite.js' {
  declare module.exports: $Exports<'discord.js-commando/src/providers/sqlite'>;
}
declare module 'discord.js-commando/src/registry.js' {
  declare module.exports: $Exports<'discord.js-commando/src/registry'>;
}
declare module 'discord.js-commando/src/types/base.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/base'>;
}
declare module 'discord.js-commando/src/types/boolean.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/boolean'>;
}
declare module 'discord.js-commando/src/types/channel.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/channel'>;
}
declare module 'discord.js-commando/src/types/command.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/command'>;
}
declare module 'discord.js-commando/src/types/float.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/float'>;
}
declare module 'discord.js-commando/src/types/group.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/group'>;
}
declare module 'discord.js-commando/src/types/integer.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/integer'>;
}
declare module 'discord.js-commando/src/types/member.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/member'>;
}
declare module 'discord.js-commando/src/types/message.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/message'>;
}
declare module 'discord.js-commando/src/types/role.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/role'>;
}
declare module 'discord.js-commando/src/types/string.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/string'>;
}
declare module 'discord.js-commando/src/types/union.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/union'>;
}
declare module 'discord.js-commando/src/types/user.js' {
  declare module.exports: $Exports<'discord.js-commando/src/types/user'>;
}
declare module 'discord.js-commando/src/util.js' {
  declare module.exports: $Exports<'discord.js-commando/src/util'>;
}
