version: '3'
services:
  bot:
    command: npm start
    env_file:
      - .env
    # always restart container on production
    restart: always

  mongo:
    ports:
      - 27018:27017

  # Enable backup in production
  mongodump:
    build: ./dump
    volumes:
      - ../mongo-backup:/backup
    environment:
      CRON_SCHEDULE: "0 1 * * *"
      MONGO_HOST: mongo
      MONGO_PORT: 27018
    depends_on:
      - mongo

volumes:
  mongo-backup: