version: '3'
services:
  bot:
    build: ..
    volumes:
      - ..:/usr/app
      - /usr/app/node_modules/
    command: npm run dev
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 5858:5858
    env_file:
      - .development.env

  mongo:
    image: mongo
    ports:
      - 27017:27017
